### ISSUE TITLE
User should be able to search through all people for whom he's responsible

### ISSUE THREAD

**Issue by Turbots** [oraj-360/oraj360tool#14]
_From @SteveDZ on May 19, 2015 14:49_

Since the list with people a user can see, can become quite extensive, search functionality should be implemented which allows a user to quickly find a specific person.

In a first phase, search should be possible based on:
<ul>
<li>first name</li>
<li>last name</li>
</ul>

This implies that a search action should be implemented in the Persons REST service.

_Copied from original issue: Turbots/oraj-360-tool#2_

**Comment by KevinDaHub** [comment]
return of list of persons from which the bum is responsible of is implemented.

**Comment by KevinDaHub** [comment]
This is also implemented for Coaches, Competence Leaders and Practice Managers
