### ISSUE TITLE
As an administrator I want to add roles to a user

### ISSUE THREAD

**Issue by TYsewyn** [oraj-360/oraj360tool#23]

**Comment by JMesens** [comment]
Are the BusinessUnitManagers the administrators?

**Comment by Turbots** [comment]
As discussed in the Telegram group, my conclusion would be:
There is a difference between **application roles** (e.g. Admin, Regular user) and **functional roles** (BUM, CL, Consultant, PM, ..)

**Comment by KevinDaHub** [comment]
Two different roles are implemented. You can now add functional roles to a user and get the functional roles of a user.

**Comment by KevinDaHub** [comment]
Only the bum or RM can add hero/user roles to persons. The hero can ask the BUM/RM for authorisation to be someones hero.
